// @ts-nocheck
import { NextResponse } from "next/server";
import { createServiceClient } from "@/lib/supabase-server";
import { sendTelegram } from "@/lib/telegram";
import { observeCron } from "@/lib/cron-observer";

// Cron: 1st of every month, 08:00 UTC.
// Monthly Instagram performance report via Telegram.

async function _observedImpl() {
  const igToken = process.env.IG_ACCESS_TOKEN;
  const igId = process.env.IG_BUSINESS_ID;
  if (!igToken || !igId) {
    return NextResponse.json({ error: "IG not configured" });
  }

  const sb = createServiceClient();

  try {
    // Current followers
    const profileRes = await fetch(
      `https://graph.instagram.com/v21.0/${igId}?fields=followers_count,media_count,username&access_token=${encodeURIComponent(igToken)}`
    );
    const profile = await profileRes.json();
    const currentFollowers = profile.followers_count || 0;
    const mediaCount = profile.media_count || 0;

    // Get last month's follower count from our tracking
    const lastMonth = new Date();
    lastMonth.setMonth(lastMonth.getMonth() - 1);
    const { data: lastRecord } = await sb
      .from("ig_follower_history")
      .select("followers")
      .lte("recorded_at", lastMonth.toISOString())
      .order("recorded_at", { ascending: false })
      .limit(1);

    const lastMonthFollowers = lastRecord?.[0]?.followers || currentFollowers;
    const growth = currentFollowers - lastMonthFollowers;
    const growthPct = lastMonthFollowers > 0 ? ((growth / lastMonthFollowers) * 100).toFixed(1) : "0";

    // Posts published this month
    const monthStart = new Date();
    monthStart.setDate(1);
    monthStart.setHours(0, 0, 0, 0);
    const { count: postsThisMonth } = await sb
      .from("ig_posts")
      .select("id", { count: "exact", head: true })
      .eq("status", "published")
      .gte("published_at", monthStart.toISOString());

    // Comments replied to
    const { count: repliesThisMonth } = await sb
      .from("ig_comment_replies")
      .select("id", { count: "exact", head: true })
      .eq("status", "posted")
      .gte("replied_at", monthStart.toISOString());

    // DMs sent
    const { count: dmsThisMonth } = await sb
      .from("ig_dm_replies")
      .select("id", { count: "exact", head: true })
      .gte("sent_at", monthStart.toISOString());

    // Photo stock
    const { count: unusedPhotos } = await sb
      .from("ig_photos")
      .select("id", { count: "exact", head: true })
      .is("used_in_post_id", null);

    const report = `📊 <b>Monthly Instagram Report</b>
━━━━━━━━━━━━━━━━━━━━

👥 <b>Followers:</b> ${currentFollowers.toLocaleString()}
📈 <b>Growth:</b> ${growth >= 0 ? "+" : ""}${growth} (${growthPct}%)
📸 <b>Total posts:</b> ${mediaCount}

<b>This month:</b>
• Posts published: ${postsThisMonth || 0}
• Comment replies: ${repliesThisMonth || 0}
• DMs sent: ${dmsThisMonth || 0}

📷 <b>Photo stock:</b> ${unusedPhotos || 0} remaining
${(unusedPhotos || 0) <= 10 ? "⚠️ LOW — add more photos!" : "✅ Healthy"}

━━━━━━━━━━━━━━━━━━━━
<i>Auto-generated by GY Command</i>`;

    await sendTelegram(report);

    // Record current followers for next month's comparison
    await sb.from("ig_follower_history").insert({
      followers: currentFollowers,
      recorded_at: new Date().toISOString(),
    }).catch(() => {});

    return NextResponse.json({
      ok: true,
      followers: currentFollowers,
      growth,
      postsThisMonth: postsThisMonth || 0,
    });
  } catch (err) {
    return NextResponse.json({ error: err.message });
  }
}


// Observability wrapper — records success/error/skipped/timeout
// outcomes to settings KV for the Thursday ops report.
export async function GET(...args: any[]) {
  return observeCron("instagram-monthly-report", () => (_observedImpl as any)(...args));
}
